AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Multi-Agent CTI Ingestion Pipeline with Financial Guardrails

Resources:
  CtiDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: cti-dependencies-layer
      Description: AI and Data processing libraries (Langchain, Pandas, etc.)
      ContentUri: cti_dependencies/
      CompatibleRuntimes:
        - python3.13
    Metadata:
      BuildMethod: python3.13
  # GUARDRAIL 1: Create the Dead-Letter Queue (DLQ) first
  CtiFailedMessagesDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CTI-Failed-Messages-DLQ-SAM

  # Create the Main Queue and attach the DLQ
  CtiIngestionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CTI-Ingestion-Queue-SAM
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CtiFailedMessagesDLQ.Arn
        maxReceiveCount: 3  # If it fails 3 times, send it to the DLQ

  # Create the Lambda Worker
  CtiLambdaWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CTI-Lambda-Worker-SAM
      CodeUri: src/ 
      Handler: lambda_worker.lambda_handler
      Runtime: python3.13
      Timeout: 180 
      MemorySize: 512
      Layers:
        - !Ref CtiDependenciesLayer
      
      # GUARDRAIL 2: Enforce the Concurrency Limit
      #ReservedConcurrentExecutions: 5 # AWS will never run more than 5 parallel workers
      
      Role: arn:aws:iam::893061520054:role/redteam-backend-CtiLambdaWorkerRole-NP6v7y5m6wEy
      
      Environment:
        Variables:
          BEDROCK_MODEL_ID: "meta.llama3-8b-instruct-v1:0"
          DB_HOST: !GetAtt CtiDatabase.Endpoint.Address
          DB_NAME: "postgres"
          DB_USER: "cti_admin"
          DB_PASSWORD_PARAM: "CTI_DB_PASSWORD"

      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CtiIngestionQueue.Arn
            BatchSize: 1 
      
  # Create the PostgreSQL Database
  CtiDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro # Free-tier eligible
      Engine: postgres
      EngineVersion: "15"
      AllocatedStorage: 20
      MasterUsername: cti_admin
      MasterUserPassword: "{{resolve:ssm-secure:CTI_DB_PASSWORD:1}}" # Securely fetches from AWS Secrets Manager
      PubliclyAccessible: true


          